### PR TITLE
feat: Add missed tags

### PR DESCRIPTION
**Pull request by MaxymVlasov**
## what

Add tags to resources where they missed

### CODE REVIEW

**Comment by gberenice** [comment]
@MaxymVlasov thanks for your contribution!

Can I ask you to add the descriptions (listed below) to `examples/complete/outputs.tf` to satisfy the failed check:
>Running output-descriptions in /__w/terraform-aws-guardduty/terraform-aws-guardduty/examples/complete
guardduty_detector is missing a description
sns_topic is missing a description

**Comment by MaxymVlasov** [comment]
@gberenice sure. Add same descriptions as for actual outputs

**Review by gberenice — APPROVED** [review]
LGTM, thank @MaxymVlasov 👍

**Comment by MaxymVlasov** [comment]
@gberenice something weird happen. it was released as v0.1.0, not as v0.7.0
https://github.com/cloudposse/terraform-aws-guardduty/releases

**Comment by gberenice** [comment]
@MaxymVlasov yeah, this is weird. I couldn't publish a release manually either; I reported this issue to @cloudposse/contributors channel.

**Pull request merged**
